spring:
  application.name: ecommerce

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    mapping-resources:
      - META-INF/common-orm.xml
      - META-INF/account-orm.xml
      - META-INF/customer-orm.xml
      - META-INF/category-orm.xml

jwt:
  secret: VmVyeVBvd2VyZnVsU2VjcmV0S2V5Rm9fjdklafidfdmnfaicnxiouRpb25SZW1lbWJlcgfdasfsafsdfdsfaffdfadfafsadfasfsdafd==
  access-token-ttl: 1800000
  refresh-token-ttl: 604800000